@startuml communication

component user_device {
    component client
    component display
}
[brokerMQTT]
component rasp {
    component camera
    component server
}

client --> brokerMQTT : 1.takePicture
brokerMQTT --> server : 2.takePicture
server --> camera : 3.takePicture
camera --> server : 4.picture
server --> brokerMQTT : 5.picture
brokerMQTT --> client : 6.picture
client --> display : 7.show

@enduml